### ISSUE TITLE
remove link to user voice site in footer

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#191]
We still link to our dead user voice site from the "Consult our Support Knowledge Base" link in the footer.

**Comment by JonathanReeve** [comment]
Ah, the old cbox-mla-blog theme. There are so many problems with that theme that I redesigned it  from scratch for 3.0. Most of the issues there are "wontfix," since they're all fixed by the 3.0 version, but since the new theme won't be released until Sentimental, this one looks like a good candidate for a bugfix release of cbox-mla-blog for Epistolary.

**Comment by JonathanReeve** [comment]
Moved to mlaa/cbox-mla-blog#28.
