### ISSUE TITLE
Add icon to notifications bubble

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-mla#193]
Adding an icon to the notifications bubble in the admin bar would widen the target and hep identify its function.

**Comment by JonathanReeve** [comment]
Cool. How about [testimonial](https://developer.wordpress.org/resource/dashicons/#testimonial)? A bell icon would be nice, since that usually stands for notifications, and [comments](https://developer.wordpress.org/resource/dashicons/#admin-comments) might already be in use if the user is a site admin with comments to be moderated.

**Comment by JonathanReeve** [comment]
![selection_454](https://cloud.githubusercontent.com/assets/1843676/5634097/0af126a2-95ab-11e4-9e84-0cbe352abc04.png)

**Comment by chriszarate** [comment]
Could the icon go inside the bubble? That way it enlarges the target and strengthens the association.

**Comment by JonathanReeve** [comment]
Sure. On: 

![selection_459](https://cloud.githubusercontent.com/assets/1843676/5648099/f7bf78fe-9659-11e4-9adb-960456d23029.png)

Off: 

![selection_460](https://cloud.githubusercontent.com/assets/1843676/5648100/fb87cba8-9659-11e4-92b3-1c958943903e.png)
