### ISSUE TITLE
Group count is not reported correctly

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#199]
In the left-hand bar, my group count is 27. The list view says "Viewing group 1 to 15 (of 15 groups)"

![27 groups](https://cloud.githubusercontent.com/assets/7083891/5649004/dfd24c88-9660-11e4-9eb0-fecedd82d0fb.png)
![15 groups](https://cloud.githubusercontent.com/assets/7083891/5649006/e17ad53c-9660-11e4-8a44-c60e87499ded.png)

**Comment by JonathanReeve** [comment]
Are the 15 groups all of a certain type, like Discussion Groups? I think this might be a duplicate of #176. What might be happening is you have a group filter on, and somehow that filter is persistent to your activity area groups list, so that your actual group count is 27, but you're viewing a subset of groups based on the filter you may have selected in the group directory. Try this: 
 * go to the groups directory (/groups)
 * click the "all groups" tab 
 * manually set all the filters to "all" 
 * go back to your activity area groups listing (/members/you/groups), and see if the numbers match up

Or, if that doesn't work, try deleting your cookies (on Firefox you can delete only the ones from the Commons so you don't lose your logged-in status elsewhere) and trying again to see if these numbers match up.

**Comment by terrainsvagues** [comment]
The first approach didn't work, but the deleting cookies did. Thanks @JonathanReeve.

**Comment by JonathanReeve** [comment]
Cool. I'll chalk this up as a duplicate of #176 then, since I think it has something to do with filters sticking in cookies.
