### ISSUE TITLE
Global scope for site search (/site-search/)

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-mla#204]
On the site-wide search page (/site-search), is it possible to have a default global scope in the dropdown list? Right now there is no global scope and the default selection is members. For someone going to that page expecting a global search, they will have unexpected results.

**Comment by JonathanReeve** [comment]
As far as I know, there's no great solution to searching everything in BuddyPress at the moment. The solution that comes the closest, I think, is [this one](http://buddydev.com/buddypress/buddypress-globalsitewide-unified-search-update-for-buddypress-1-5/), [on github here](https://github.com/sbrajesh/bp-global-unified-search). To get this working, the process would be: 
 * update the plugin for the latest BP/WP
 * add provisions to the plugin for searching content types that aren't already searched (files? group blogs?)
 * style a search results page with reasonably similar ways of displaying content types: 
  - members
  - groups
  - forum posts?
  - files 
  - blog posts

I imagine this could be a BuddyPress plugin and a patch to cbox-theme. 

Alternatively, Boone seems to be working on [an Elasticsearch plugin for BuddyPress](https://github.com/boonebgorges/bpes), but I don't know what state the project is in. @boonebgorges, do you have any ideas about what a global BP/CBOX search might look like?

**Comment by boonebgorges** [comment]
I'm still working on the Elasticsearch plugin - I have a client who needs it in the upcoming months. I'll write about it publicly when it's in a usable state. IMHO, using an external search appliance like ES is going to be the only way to get a truly useful unified search for BP, because of the various ways that content types are stored. The downside, of course, is that this requires maintainance of an external system, but for installs like MLA's, this is maybe not such a big deal.

**Comment by chriszarate** [comment]
Neat. ES is :sunglasses:. Looking forward to that.

**Comment by terrainsvagues** [comment]
Possibly related issue: from both within the site-wide search (with dropdown option "members") and the member directory, a search for ["Virginia"](http://commons.mla.org/members/?s=virginia) will yield results for members with "Virginia Woolf" as an interest, or from the University of Virginia, rather than only members *named* Virginia. As no context is provided to the member searching, the result seems very broken indeed.

**Comment by terrainsvagues** [comment]
Rosemary: "Why can't it just search the site? I was interested in finding out the places where the forum structure is explained. Couldn't do it."

**Comment by JonathanReeve** [comment]
Putting this on hold, waiting to see how Boone's plugin will work. Very excited to see how it will work!

**Comment by JonathanReeve** [comment]
Testing [Buddypress Global Search](https://wordpress.org/plugins/buddypress-global-search/), which seems to be working so far, except for the typeahead dropdown menu, which I can't get to work yet.

**Comment by terrainsvagues** [comment]
See also #282

**Comment by JonathanReeve** [comment]
Global search now working on dev. Searches groups, members, discussion threads, activity, posts, and looks like it might even have support for searching messages. As far as I can tell, it respects privacy settings as expected.
