### ISSUE TITLE
Add analytics widget for member sites

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#214]
A couple of members mentioned that they would like to be able to see which of their posts were getting the most traffic, etc. When told about Google analytics, they claimed the process sounded much too complicated. Is there a widget or plug-in we can make available to them?

**Comment by JonathanReeve** [comment]
You could point users to [the guide on the help blog](http://howtouse.commons.mla.org/2013/06/06/using-google-analytics-on-your-blog/), if you haven't already--that makes the process look relatively painless, in my opinion. As I understand it, it's just: 1. get an analytics user ID from Google, and 2. enter the ID in your site's dashboard. As far as I know, there aren't any analytics plugins that don't leverage an external analytics service, even Jetpack, so I suspect they're all going to require the same amount of configuration as our Google Analytics plugin. But if you come across any, let me know. My attempt to search for non-Google analytics on the WP Plugins registry (`analytics -google site:http://wordpress.org/plugins/`) returned zero results, but there might be one out there somewhere.

**Comment by terrainsvagues** [comment]
Yes, I'm working on revamping & simplifying the language there. But I think they want to be able to see the analytics from within WP, without going elsewhere. Perhaps we could just offer this: https://wordpress.org/plugins/google-analytics-dashboard-for-wp/

**Comment by JonathanReeve** [comment]
I tried installing that one earlier, and the user-side configuration process looks much more complicated--in addition to providing a Google Analytics user number, the user has to provide an API key and secret, since for it to display analytics data in the WP dashboard, it requires the additional step of sending analytics data from GA back to WP. I'll keep an eye out for other analytics plugins, though.

**Comment by chriszarate** [comment]
Looking at the README for Nicky's suggested plugin, it references "Mode 2," which sounds promising: "network activated while authorizing an entire WordPress Network using a single Google Analytics account. You'll be able to assign a property/view to each site, from your Network Admin screen." Is that what you tried or should we investigate further?

**Comment by JonathanReeve** [comment]
I didn't get that far--I gave up when it asked for API keys/secrets. But I'll give it another shot.

**Comment by JonathanReeve** [comment]
So I did some more experimenting with this plugin, and it looks like user sites can be set up to use our Google Analytics account, but a super-admin has to manually configure each site by 1. setting up a "property" in Google Analytics for that subdomain, and 2. configuring the plugin to use that subdomain's GA property in the network dashboard. This comes with a few caveats: 
 * since there doesn't seem to be an easy way to automate this for all sites, we'd have to do this on a case-by-case basis, i.e., if site administrators request this specifically for their site. 
 * sites that aren't configured with a GA "property" for their subdomain will default to viewing analytics for the parent site, so we'd effectively be publicizing analytics for the greater Commons site, unless we could figure out a way to enable this plugin for only those sites that request it, and disable it elsewhere. 
 * I don't know if or how this would conflict with our existing GA plugin, and whether it would conflict with current use our GA plugin. It would probably be OK, but if there were two analytics.js instances making external requests, it could slow down load time a little, and I imagine it could be confusing for users that see two "Google Analytics" tabs in their site admin dashboards. 
 * GA only allows 50 "properties" per account, so we'd only be able to do this for up to 50 sites. 

Given all this, I'd vote for skipping this issue, since it seems like a lot of trouble for the seemingly narrow use-case of a site administrator that wants analytics, but also doesn't want to do the configuration required to enable it. But I agree that it'd be cool if site admins had easier access to usage charts, and so I'd be open to other opinions.

**Comment by terrainsvagues** [comment]
Another user request for this to be available in the dashboard.

**Comment by terrainsvagues** [comment]
https://wordpress.org/plugins/stats-counter/ ?

**Comment by chriszarate** [comment]
Good news (via bad news)! I had to disable the plugin we were using—it was basically abandonware and someone posted a vulnerability. 

Good news is that I found a pretty good replacement—now installed. Take a look at Dashboard > Statistics on one of your sites. Every site admin has access to this for their sites.
