### ISSUE TITLE
"sign up" or "registration" link? 

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#217]
There has been some confusion about logging in to the Commons for first-time users. Some of this will be mitigated with the new copy on our log-in screen, "Log in with your MLA credentials," (mlaa/cbox-auth#3) but it might also help to be clearer about this. Some possible solutions for discussion: 

 * we could add a "sign up" button next to the "log in" button fairly easily, and have it just link to https://www.mla.org/join_new_intro. 
 * we could change the "Log In" button to read "Log In or Register," and change the "Forgot your login information?" link on the resulting page to something like "Forgot your log-in information, or want to join?" The target of the link could stay the same, since http://www.mla.org/login has a section called "Become a Member" with a link that reads "Not a member? Join the MLA."

**Comment by terrainsvagues** [comment]
* I like the idea of two buttons, but I don't think the "register" should link to the join page, since we're really suggesting people sign up for the Commons. Both buttons would need to say "with your MLA credentials" — which could take up a lot of space. 
* So perhaps one button, "Log in or sign up with your MLA credentials" with some way of detecting if they've been on the site before (on the same browser, without clearing cookies...) determining whether they get taken to the mla.org login page or the commons one. But this solution would be really annoying for people logging in on different devices, browsers, etc.
* So perhaps two buttons again. Both stressing "with your MLA credentials."
*Gah.

**Comment by JonathanReeve** [comment]
I like the idea of making registration (i.e. becoming an MLA member) clearer, but I think we need a way to do this cleanly and concisely. Two buttons, both stressing "with your MLA credentials," is, I think, way too busy:  

![selection_033](https://cloud.githubusercontent.com/assets/1843676/8107512/c3d02998-1017-11e5-9cb3-718f0daa6d6f.jpg)

And it still doesn't solve the original issue that non-members might be confused about how to register for the site, (i.e. become an MLA member). That is, non-members don't have MLA credentials, so we're back where we started. 

Let's talk about this at the next meeting.

**Comment by JonathanReeve** [comment]
Two buttons: "Join the MLA" and "MLA Member Login"

**Comment by JonathanReeve** [comment]
![selection_034](https://cloud.githubusercontent.com/assets/1843676/8166234/8440b810-1364-11e5-9fc8-7afdd8381784.jpg)


Suggestions for other [dashicons](https://developer.wordpress.org/resource/dashicons/) are welcome.
