### ISSUE TITLE
validate academic interests field

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#235]
Members consistently mess up the academic interests field of their profiles by having long descriptors, joining subjects with "and," or cutting and pasting sentences from their CVs. This means they miss out on the networking possibilities allowed by entering the fields correctly. We should tell them how to do this on the edit extended profile page, probably via a coachmark that appears when they hover over the "+ Academic Interests" button.

**Comment by JonathanReeve** [comment]
Does the placeholder text already do this? 

![selection_506](https://cloud.githubusercontent.com/assets/1843676/6402649/45119b38-bdd7-11e4-96b3-58cf828107d7.png)

Some of the interests that appear on portfolios were entered before the extended profile system was released, so they may not have benefited from the above placeholder text. (And indeed, owing to the previous field description "tell us something about yourself!", many aren't academic interests at all.)

**Comment by terrainsvagues** [comment]
The placeholder text does not appear if a user tries to edit his/her profile, though.

**Comment by JonathanReeve** [comment]
I see. So if a user already has an "Academic Interests" field (imported from the previous profile system), then they won't see this placeholder text. But also, if they already have this field filled out, they won't be clicking the "+ Academic Interests" button, since they already have the field (and the button will be grayed out). So the placeholder text obviates the need for a hover tooltip, I think, but doesn't solve the problem of users with existing profile data. 

Options for fixing that might include: 
 * moving the placeholder text underneath the field titles (not ideal, since it might clutter up the interface and make mobile design difficult)
 * some kind of validation on click-away from that field, that could check if there's a long string of text with no commas and could warn "please include at least two interests, and separate them with a comma."

**Comment by JonathanReeve** [comment]
Validation makes the most sense to me here. I'll change the title to reflect that. Slating this for 3.0.

**Comment by terrainsvagues** [comment]
If we go for a typeahead model à la CORE (see #94), that might obviate the need for the validation. This card is dependent on what we do there, I think.

**Comment by JonathanReeve** [comment]
You're right. Let's keep #94 as the plan and close this one.

**Comment by JonathanReeve** [comment]
Whoops, I'm guessing you mean mlaa/cac-advanced-profiles#94, not cbox-mla 94.
