### ISSUE TITLE
[Invite Anyone] non-super-admins unable to use "invite anyone" via "Send Invites" group tab

### ISSUE THREAD

**Issue by kshkim** [mlaa/cbox-mla#256]
![s - send invites - mla commons clipular](https://cloud.githubusercontent.com/assets/8835589/7231860/0f2d6e78-e746-11e4-8dbd-ded7fa46a9d8.png)

**Comment by JonathanReeve** [comment]
Turns out this was an admin option in Dashboard -> Settings -> Invite Anyone. Here's what I did: 
 * Effectively disabled email invitaitons, since this opens up a whole string of new issues. 
 * Allowed anyone to send group invitations to anyone, provided they're a member of the group. 
 * Limited number of invites to 10.
