### ISSUE TITLE
cannot update committee email subscription defaults

### ISSUE THREAD

**Issue by kfitz** [mlaa/cbox-mla#269]
I am both a superadmin and an admin for the NVS committee, so this should not be a permissions issue. When I attempt to update the email subscription defaults for the committee, I get a set of radio buttons but no "save" button, so nothing happens. See https://commons.mla.org/groups/committee-on-the-new-variorum-edition-of-shakespeare/admin/group-settings/

![screen shot 2015-05-13 at 10 01 42 am](https://cloud.githubusercontent.com/assets/3170201/7612177/34e69ef0-f957-11e4-9784-39d51b05fa11.png)

**Comment by JonathanReeve** [comment]
This appears to be because: 
 1. [this commit](https://github.com/mlaa/cbox-mla/commit/1c3bc5e385ce82eee7d8bcc1ba6d9f48c9787227#diff-957fe1779a791061d7c73baa21d1c1b1R56) and corresponding cbox-auth commits hide settings for MLA forums and committees, which prevents committee admins from changing the privacy of a committee. This hides the save button if it detects that there are no settings sections here to save.   
 2. the plugin `buddypress-group-email-subscription` adds a section here outside of the hidden sections from 1. 
 3. the save button won't display, since it doesn't detect the newly-added settings section.

**Comment by JonathanReeve** [comment]
Enabling the save button still doesn't allow group email subscription settings to be saved. It looks like this is happening on a vanilla CBOX install, too. I'll file a bug report upstream.

**Comment by JonathanReeve** [comment]
It turns out that group email subscriptions settings are in fact saved, but not if the value is "no email"--in that case, the groupmeta entry for default subscription is deleted. This would be fine if the default default value for this option were "no email," but since I changed the default default value to "daily" in f699443cdf1ae2068b763c06340a3100ee768d7d, this means that changing the default email subscription level to "no email" won't work--the radio button will simply revert to the default default level, which in this case is "daily." I'll close this issue as fixed and open a new one for that more specific issue.

**Comment by JonathanReeve** [comment]
Fixed in 97a00a5. Moving the issue described above to #270.
