### ISSUE TITLE
Improve Navigability & Organization of Files

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#290]
Given that all committee materials will be moving to the Commons in October, we need to have a more robust and user-friendly way of displaying those materials (and files in general). Nesting, color coding, general organization and searchability.

**Comment by JonathanReeve** [comment]
Since our current Files plugin doesn't (and won't) support things like folders, we'd need a different plugin. The process seems like it could be broken down into these stages: 

 1. Identify a new files plugin that is well-maintained and has the greatest number of desired features. BuddyDrive, maybe? 
 2. Add new features. I haven't tested it, but it doesn't look like BuddyDrive has color coding, and might not have search capabilities, either. In that case, we'd need to fork the plugin and add those features. 
 3. Figure out what to do about existing files plugins. Do we try to migrate existing files to the new system? If so, how do we do that?

**Comment by chriszarate** [comment]
I have BuddyDrive running on an old suspended dev VM. I'll fire it up.

**Comment by chriszarate** [comment]
If we have a files plugin with good organization, do we need integration in global search? Or, do we need it for 3.0?

I think migrating existing files is a priority. (Which is really just migrating the metadata, the files themselves are on the FS.)

**Comment by JonathanReeve** [comment]
Yep, we would need integration with global search. That *might* not be too tricky to pull off, since all the global search types are modular.

**Comment by JonathanReeve** [comment]
From [this support forum topic](https://wordpress.org/support/topic/search-buddydrive) from a few days ago, it looks like BuddyDrive doesn't have search capabilities, although the developer is talking about adding them in a future version. Color-coding doesn't seem like it's a current or planned feature. Folders exist, but they aren't infinitely hierarchical--you can't have folders within folders. Reminds me of MacOS < 4.0 with MFS. 

Should we: 
 1. go with BuddyDrive as-is
 2. go with BuddyDrive, but only after adding desired features
 3. go with some other plugin entirely

**Comment by JonathanReeve** [comment]
See also #308

**Comment by terrainsvagues** [comment]
Just re-upping the priority on this one. Chris is testing.
