### ISSUE TITLE
Suggest Groups by Filters

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#292]
Could we use this to suggest groups based on academic interests? https://wordpress.org/plugins/bp-groups-suggestions/ 

"By default, the plugin uses the user's friends's groups in order to suggest groups of the login user, but this can be extended throughout available filters. "

**Comment by JonathanReeve** [comment]
:+1:. I'm not sure I'm sold on the idea of its creating a new tab, but I can't think of a better way, either. 

Hacking it to understand academic interests and associate them with groups would be tricky, but would be a lot easier if we used the interest taxonomy @rekmla suggested in mlaa/cac-advanced-profiles#91. We could easily map interests in that list with groups, since they roughly correspond to MLA forums, anyway. New (unknown) interests would be a little harder to parse.

**Comment by JonathanReeve** [comment]
Instead of adding a tab, we could also add suggested groups to the groups displayed in the My Groups tab, so long as they had some kind of markings to indicate that they were suggested.

**Comment by JonathanReeve** [comment]
The BP Group Suggestion plugin doesn't work quite right out of the box. It seems to work on other themes, but conflicts with our custom tab AJAX setup. This will take some work to shoehorn in.
