### ISSUE TITLE
welcome/help blog is out of date

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#71]
Screenshots on http://howtouse.commons.mla.org/ are out of sync with the new theme.

**Comment by terrainsvagues** [comment]
In our meeting tomorrow, I would like to discuss how we can tighten up all of these scattered bits of information and put them in one place, either how to use or FAQ (this includes getting rid of the Help and How-To group and editing the Getting Started page).

**Comment by terrainsvagues** [comment]
These files are all now in Google Drive to be edited, condensed, and put through TRAC for editorial review. The FAQ should be merged with the help files, which, once copy is complete, will be organized according to what a user might want to do.

**Comment by kshkim** [comment]
More posts to be updated due to admin bar (perhaps the how to use posts can get updated first in the Google Drive version):
* [ ] FAQ posts that need to be updated bc of admin bar
 - [ ] http://faq.commons.mla.org/2012/12/06/how-do-i-upload-a-picture-of-myself-to-use-within-the-site/
 - [ ] http://faq.commons.mla.org/2012/12/06/how-can-i-edit-my-portfolio/
* [ ] http://howtouse.commons.mla.org/category/how-to-do-things-with-mla-commons/blogs/
 - [ ] Anything that shows WordPress has an outdated admin bar

**Comment by JonathanReeve** [comment]
[The page about footnotes](https://howtouse.commons.mla.org/2013/05/08/using-footnotes/) will need to be updated soon, since a) the current plugin, "jQuery Hover Footnotes" doesn't really work with CommentPress anymore, and b) we might install a new footnotes plugin, FD Footnotes that may end up replacing jQuery Hover Footnotes.
